"""
USES: Traffic Multiplier Model Trainer.
SUPPORT: Loads the synthetic CSV dataset, trains a Random Forest Regressor, and serializes the model to a .joblib file for production inference.
"""
import pandas as pd  # Import pandas for data loading and feature selection
from sklearn.ensemble import RandomForestRegressor  # Import the core regression algorithm
from sklearn.model_selection import train_test_split  # Import utility for validation splitting
from sklearn.metrics import mean_absolute_error  # Import metric for accuracy assessment
import joblib  # Import utility for saving the trained model object to disk
import os  # Standard library for directory management
from ml.traffic_model import TrafficModelMetadata  # Import metadata for feature consistency

def train_traffic_model():  # Main training orchestration function
    """
    Trains and saves the Traffic Prediction model.
    """
    # Step 1: Data Acquisition
    input_path = "ml_models/training_data.csv"  # Target dataset generated by the generator script
    if not os.path.exists(input_path):  # Check if training data exists
        print(f"Error: {input_path} not found. Run generate_dataset.py first.")  # Log error
        return  # Abort training

    df = pd.DataFrame(pd.read_csv(input_path))  # Load CSV data into a pandas DataFrame
    
    # Step 2: Feature Engineering & Selection
    # Extract only the columns defined in the production metadata for consistency
    X = df[TrafficModelMetadata.FEATURES]  # Independent variables (Hour, Day, etc.)
    y = df['multiplier']  # Dependent variable (The congestion factor to predict)

    # Step 3: Train/Test Split
    # Withhold 20% of data to test how well the model generalizes to new scenarios
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

    # Step 4: Model Initialization
    # We use Random Forest because it handles non-linear traffic peaks effectively
    model = RandomForestRegressor(
        n_estimators=100,  # Build 100 individual decision trees
        max_depth=10,  # Limit tree depth to prevent over-fitting to noise
        random_state=42  # Ensure reproducible training results
    )

    # Step 5: Model Fitting
    print("Training Random Forest model...")  # Log progress
    model.fit(X_train, y_train)  # Execute the training algorithm

    # Step 6: Evaluation
    # Calculate Mean Absolute Error (MAE) to understand the average prediction deviation
    predictions = model.predict(X_test)  # Run model on hidden test data
    mae = mean_absolute_error(y_test, predictions)  # Compare predictions with ground truth
    print(f"Model Training Complete. MAE: {mae:.4f}")  # Log accuracy metric

    # Step 7: Serialization
    # Save the trained model to the production path for the predictor to load
    os.makedirs("ml_models", exist_ok=True)  # Ensure the target directory exists
    joblib.dump(model, "ml_models/traffic_predictor.joblib")  # Save model as a joblib file
    print("Model saved to ml_models/traffic_predictor.joblib")  # Log final success

if __name__ == "__main__":  # Entry point check
    train_traffic_model()  # Execute the training script
